on: [ push, pull_request ]

name: Continuous integration

jobs:
  build:
    name: Build And Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
      - run: wasm-pack build && wasm-pack test --chrome --firefox --headless
